name: 'CapRover Clickiwoo Deploy'
description: 'Action to deploy on Caprover server'
author: 'Clickiwoo'
branding:
  icon: upload-cloud
  color: orange
inputs:
  token:
    description: "GITHUB_TOKEN"
    required: true
  server:
    description: "Captain URL for your CapRover server."
    required: true
  password:
    description: "Admin password for your CapRover server."
    required: true
  app:
    description: "Application name to deploy this repo to, must have been created."
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:${{ github.sha }}

    - run: |
        echo "Deploying on CapRover..."
        docker run caprover/cli-caprover:2.2.3 caprover deploy -u ${{ inputs.server }} -p '${{ inputs.password }}' -a ${{ inputs.app }} -i ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:${{ github.sha }}

      shell: bash